# Generated by Django 3.0.6 on 2020-05-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200523_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
