# Generated by Django 3.0.6 on 2020-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_delete_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
