# Generated by Django 3.0.6 on 2020-05-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='response_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
