# Generated by Django 3.0.6 on 2020-05-24 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200523_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 9, 20, 4, 604302, tzinfo=utc), verbose_name='time answered'),
        ),
    ]
