# Generated by Django 3.0.6 on 2020-05-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_choice_is_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.CharField(max_length=2000)),
                ('pika_exp', models.CharField(max_length=2000)),
                ('remarks', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(verbose_name='response time')),
            ],
        ),
    ]
